// GENERATED by FlutterFire-equivalent setup. Client config values
// (not secrets — they ship in the app binary; security is enforced by Firestore
// rules + App Check). Safe to commit. See docs/FIREBASE_SETUP.md.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEMqMFAeK2vEfXQ0UIK4JSzCzhdyZgSI',
    appId: '1:397994773229:android:abd0e820e8ef82adc9dae4',
    messagingSenderId: '397994773229',
    projectId: 'kidssafecam',
    storageBucket: 'kidssafecam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdgj0RmFgRoJlTuSk1paD0DEOvkh5i_U',
    appId: '1:397994773229:ios:e9260a5b5afea0c0c9dae4',
    messagingSenderId: '397994773229',
    projectId: 'kidssafecam',
    storageBucket: 'kidssafecam.firebasestorage.app',
    iosBundleId: 'com.kidssafecam.parent',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDhFsmFTgm43LtxHZm1AvJLDQVGmB9g8',
    appId: '1:397994773229:web:9f4c155fa815868cc9dae4',
    messagingSenderId: '397994773229',
    projectId: 'kidssafecam',
    authDomain: 'kidssafecam.firebaseapp.com',
    storageBucket: 'kidssafecam.firebasestorage.app',
  );
}
