import 'package:ai_baby_monitor_shared/ai_baby_monitor_shared.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/router.dart';
// Generated by `flutterfire configure --project=kidssafecam`.
// Not committed (git-ignored). See docs/FIREBASE_SETUP.md.
import 'firebase_options.dart';

/// Entry point for the Parent app.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: ParentApp()));
}

class ParentApp extends StatelessWidget {
  const ParentApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Baby Monitor',
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      routerConfig: parentRouter,
      debugShowCheckedModeBanner: false,
    );
  }
}
